# Generated by Django 2.2.28 on 2024-03-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melodyMeter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='albumID',
            new_name='album',
        ),
    ]
