# Generated by Django 2.2.28 on 2024-03-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melodyMeter', '0003_auto_20240306_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
