# Generated by Django 2.2.28 on 2024-03-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melodyMeter', '0005_auto_20240311_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='test',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
