# Generated by Django 2.2.28 on 2024-03-11 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melodyMeter', '0006_album_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='test',
        ),
    ]
