# Generated by Django 2.2.28 on 2024-03-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melodyMeter', '0007_remove_album_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
