# Generated by Django 4.2.11 on 2024-03-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("melodyMeter", "0008_album_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="year",
            field=models.IntegerField(default=0),
        ),
    ]
