# Generated by Django 4.2.11 on 2024-03-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("melodyMeter", "0009_alter_album_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="song",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
