# Generated by Django 4.2.11 on 2024-03-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("melodyMeter", "0010_alter_album_id_alter_song_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
