# Generated by Django 4.2.11 on 2024-03-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("melodyMeter", "0013_remove_song_rating_alter_userprofile_id_songrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
