# Generated by Django 4.2.11 on 2024-03-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("melodyMeter", "0014_album_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3),
        ),
    ]
